apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-worker
spec:
  replicas: 0   # REQUIRED for KEDA
  selector:
    matchLabels:
      app: hello-worker
  template:
    metadata:
      labels:
        app: hello-worker
    spec:
      containers:
      - name: worker
        image: kunalpiplani12/worker:latest
        imagePullPolicy: Always
